# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Petal-Mail
version:      0.31
version_from: lib/Petal/Mail.pm
installdirs:  site
requires:
    Encode:                        1.75
    MKDoc::XML:                    0.61
    Petal:                         1.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
